name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: ''

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        name: Cache Gradle packages
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set version
        run: |
          set -e
          NEW_VERSION="${{ github.event.inputs.version }}"
          sed -i "s/project\.externalVersion : '.*\..*\..*'/project\.externalVersion : '$NEW_VERSION'/g" build.gradle
      - name: Print new version
        run: |
          echo "$(./gradlew -q currentVersion)"

      - name: Setup git
        run: |
          set -ex
          git config --global user.email "builder+skip-ci@codota.com"
          git config --global user.name "codota-builder"

      - name: Commit changes
        run: |
          NEW_VERSION="${{ github.event.inputs.version }}"
          git pull origin master --no-edit
          git commit -am "Set meta version to $NEW_VERSION"
          git push
