name: Continues Integration

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        name: Cache Gradle packages
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build & Test
        run: ./gradlew build --scan
      - if: always()
        name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: build/reports

  compatibility-stable:
    name: Ensure plugin compatibility against IC releases 2019.3 - 2021.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build the plugin
        run: ./gradlew buildPlugin

      - name: Validate the plugin
        run: ./gradlew runPluginVerifier

  compatibility-eap:
    name: Ensure plugin compatibility against latest eap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build the plugin
        run: ./gradlew buildPlugin

      - name: Download latest EAP
        run: |
          sudo curl -L "https://download.jetbrains.com/product?code=IC&latest&distribution=linux&type=eap" --output latest-eap.tar.gz
          mkdir latest-eap && tar -xvf latest-eap.tar.gz -C latest-eap --strip-components 1
          ls -al latest-eap

      - name: Validate the plugin against latest EAP
        run: ./gradlew runPluginVerifier -PideVersions="" -PlocalPaths="$(pwd)/latest-eap"
  security:
    name: Vulnerabilities Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --configuration-matching=^releaseRuntimeClasspath$|^compile$